#!/bin/sh

SCRIPTS_DIR=$(dirname "$(realpath "$0")")
REPO=${1}
GIT_DIR="${HOME}/${REPO}"

touch "${GIT_DIR}"/git-daemon-export-ok
mkdir -p "${GIT_DIR}"/hooks/post-receive.d
ln -sf "${SCRIPTS_DIR}"/hook "${GIT_DIR}"/hooks/post-receive
ln -sf "${SCRIPTS_DIR}"/update-stagit "${GIT_DIR}"/hooks/post-receive.d/

echo "git://git.crocker.im/${REPO}" > "${GIT_DIR}/url"

if [ ! -f "${GIT_DIR}/owner" ]; then
	echo "David Crocker <david@crocker.im>" > "${GIT_DIR}/owner"
fi

if [ ! -f "${GIT_DIR}/description" ]; then
	printf 'Description: '
	read DESCRIPTION
	echo "$DESCRIPTION" > "${GIT_DIR}/description"
fi

"${SCRIPTS_DIR}"/update-stagit "${REPO}"
