#!/bin/sh
DATA=$(cat)
EXIT_CODE=0
HOOK_NAME=$(basename "$0")
GIT_DIR=${GIT_DIR:-$(pwd)}

for HOOK in "${GIT_DIR}/hooks/${HOOK_NAME}".d/*; do
	[ -x "$HOOK" ] || continue
	echo "$DATA" | "$HOOK"
	EXIT_CODE=$((EXIT_CODE + $?))
done

exit $EXIT_CODE
