#!/bin/sh
#
# Git hook that iterates over hook scripts in a corresponding directory.
#
# e.g. If the hook's name is post-receive, it will call all scripts in the
# post-receive.d directory

DATA=$(cat)
EXIT_CODE=0
HOOK_NAME=$(basename "$0")
GIT_DIR=${GIT_DIR:-$(pwd)}

for HOOK in "${GIT_DIR}/hooks/${HOOK_NAME}".d/*; do
	[ -x "$HOOK" ] || continue
	echo "Running ${HOOK_NAME} hook: ${HOOK}"
	echo "$DATA" | "$HOOK"
	EXIT_CODE=$((EXIT_CODE + $?))
done

exit $EXIT_CODE
