#!/bin/sh

SCRIPTS_DIR=$(dirname "$(realpath "$0")")
GIT_DIR="${HOME}/${1}"

mkdir -p "${GIT_DIR}/hooks/post-receive.d"
ln -sf "${SCRIPTS_DIR}/hook" "${GIT_DIR}/hooks/post-receive"
ln -sf "${SCRIPTS_DIR}/deploy-repo" "${GIT_DIR}/hooks/post-receive.d/"
