#!/bin/sh
#
# usage: $0 [name]
#
# if name is not set the basename of the current directory is used,
# this is the directory of the repo when called from the post-receive script.

# NOTE: needs to be set for correct locale (expects UTF-8) otherwise the
#       default is LC_CTYPE="POSIX".
export LC_CTYPE="en_US.UTF-8"

ishook=0
name="$1"
if test "${name}" = ""; then
	ishook=1
	name=$(basename "$(pwd)")
fi

reponame=$(basename "$name")

# config
# paths must be absolute.
reposdir="/home/git"
dir="${reposdir}/${name}"
htmldir="/var/www/git.crocker.im/html"
stagitdir="/"
destdir="${htmldir}${stagitdir}"
cachefile=".htmlcache"
# /config

update-stagit-index()
{
	find "$reposdir" -type f -name git-daemon-export-ok |
		xargs -d '\n' dirname |
		xargs -d '\n' stagit-index > "${destdir}/index.html"
}

if ! test -d "${dir}"; then
	echo "${dir} does not exist" >&2
	exit 1
fi
cd "${dir}" || exit 1

# Only build pages for published repos
if ! test -f "git-daemon-export-ok"; then
	update-stagit-index
	# Remove published HTML
	rm -rf "${destdir}/${reponame}"
	exit 0
fi

# Set a URL if none exists
if ! test -f "url"; then
	echo "git://git.crocker.im/${name}" > url
fi

# Set an owner if none exists
if ! test -f "owner"; then
	echo "David Crocker <david@crocker.im>" > owner
fi

# detect git push -f
force=0
if test "${ishook}" = "1"; then
	while read -r old new ref; do
		test "${old}" = "0000000000000000000000000000000000000000" && continue
		test "${new}" = "0000000000000000000000000000000000000000" && continue

		hasrevs=$(git rev-list "${old}" "^${new}" | sed 1q)
		if test -n "${hasrevs}"; then
			force=1
			break
		fi
	done
fi

printf "[%s] stagit HTML pages... " "${reponame}"

mkdir -p "${destdir}/${reponame}"
cd "${destdir}/${reponame}" || exit 1

# remove commits and ${cachefile} on git push -f, this recreated later on.
if test "${force}" = "1"; then
	rm -f "${cachefile}"
	rm -rf "commit"
fi

update-stagit-index

# make pages.
stagit -c "${cachefile}" "${reposdir}/${reponame}"

ln -sf log.html index.html
ln -sf ../style.css style.css
ln -sf ../logo.png logo.png
ln -sf ../favicon.png favicon.png

echo "done"
